// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsfANGzDdr9s4qveDFLxua3Ncb6Ehv4FY',
    appId: '1:620346205464:web:7e05194ac5ceb7af1f2a6d',
    messagingSenderId: '620346205464',
    projectId: 'fir-connection-fd0c1',
    authDomain: 'fir-connection-fd0c1.firebaseapp.com',
    databaseURL: 'https://fir-connection-fd0c1-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connection-fd0c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2v7WIyi-8_b1jNslIIPBnvireN25M4gY',
    appId: '1:620346205464:android:74fe29bae2ae0d5d1f2a6d',
    messagingSenderId: '620346205464',
    projectId: 'fir-connection-fd0c1',
    databaseURL: 'https://fir-connection-fd0c1-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connection-fd0c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXIXjOOfg0CP44gsYvn3l0TO9QVMgCgpw',
    appId: '1:620346205464:ios:a28885bafdf393951f2a6d',
    messagingSenderId: '620346205464',
    projectId: 'fir-connection-fd0c1',
    databaseURL: 'https://fir-connection-fd0c1-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connection-fd0c1.firebasestorage.app',
    iosClientId: '620346205464-bj94adlkbimiatpn41j4305jtghebur5.apps.googleusercontent.com',
    iosBundleId: 'com.example.reciever',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXIXjOOfg0CP44gsYvn3l0TO9QVMgCgpw',
    appId: '1:620346205464:ios:a28885bafdf393951f2a6d',
    messagingSenderId: '620346205464',
    projectId: 'fir-connection-fd0c1',
    databaseURL: 'https://fir-connection-fd0c1-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connection-fd0c1.firebasestorage.app',
    iosClientId: '620346205464-bj94adlkbimiatpn41j4305jtghebur5.apps.googleusercontent.com',
    iosBundleId: 'com.example.reciever',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsfANGzDdr9s4qveDFLxua3Ncb6Ehv4FY',
    appId: '1:620346205464:web:84b7471898ce56861f2a6d',
    messagingSenderId: '620346205464',
    projectId: 'fir-connection-fd0c1',
    authDomain: 'fir-connection-fd0c1.firebaseapp.com',
    databaseURL: 'https://fir-connection-fd0c1-default-rtdb.firebaseio.com',
    storageBucket: 'fir-connection-fd0c1.firebasestorage.app',
  );
}
